# server config
server:
   host: ${SERVER_HOST:localhost}
   port: ${SERVER_PORT:8080}
   servlet:
     context-path: ${SERVER_CONTEXT:/}
   tomcat:
     remoteip:
      remote_ip_header: ${SERVER_TOMCAT_REMOTE_IP_HEADER:x-forwarded-for}
      protocol_header: ${SERVER_TOMCAT_PROTOCOL_HEADER:x-forwarded-proto}
   max-http-request-header-size: 32000
   error:
      include-stacktrace: never

# Spring configuration
spring:
  application:
    name: db-sts
  datasource:
    sts:
      driverClassName: org.postgresql.Driver
      password: ${JDBC_PASS:}
      username: ${JDBC_USER:sts}
      url: ${JDBC_URL:}
      platform: ${JDBC_PLATFORM:postgresql}
    service:
      driverClassName: org.postgresql.Driver
      password: ${JDBC_SERVICE_PASS:}
      username: ${JDBC_SERVICE_USER:users}
      url: ${JDBC_SERVICE_URL:}
      platform: ${JDBC_SERVICE_PLATFORM:postgresql}



# Application 
application:
  endpoint: ${STS_ENDPOINT:http://${server.host}:${server.port}}
  name: @project.name@
  description: @project.description@
  version: @project.version@
logging:
   level:
      ROOT: INFO
      it.smartcommunitylabdhub: ${LOG_LEVEL:INFO}
      com.zaxxer.hikari: DEBUG
      org.hibernate: DEBUG

# STS
sts:
  credentials:
    duration: ${STS_CREDENTIALS_DURATION:28800}
    roles: ${STS_CREDENTIALS_ROLES:}
    password-length: ${STS_CREDENTIALS_PWD_LENGTH:12}
  client:
    client-id: ${STS_CLIENT_ID:}
    client-secret: ${STS_CLIENT_SECRET:}
  jwt:
    issuer-uri: ${STS_JWT_ISSUER_URI:}
    audience: ${STS_JWT_AUDIENCE:sts}
    claim: ${STS_JWT_CLAIM:roles}

